/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author akram
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnQuitter = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxRechercher = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxAjouter = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMettreAjour = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxSupprimer = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jardins de dellys"));

        jLabel1.setText("Ceci est une application pour aider a gérer un club de Jardinage");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnQuitter.setText("Quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        jMenu1.setText("Operations");

        jCheckBoxRechercher.setSelected(true);
        jCheckBoxRechercher.setText("Rechercher");
        jCheckBoxRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRechercherActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxRechercher);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jCheckBoxAjouter.setSelected(true);
        jCheckBoxAjouter.setText("Ajouter");
        jCheckBoxAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAjouterActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxAjouter);

        jCheckBoxMettreAjour.setSelected(true);
        jCheckBoxMettreAjour.setText("Mettre à Jour");
        jCheckBoxMettreAjour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMettreAjourActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMettreAjour);

        jCheckBoxSupprimer.setSelected(true);
        jCheckBoxSupprimer.setText("Supprimer");
        jCheckBoxSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSupprimerActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxSupprimer);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuitter)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnQuitter)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSupprimerActionPerformed
        new SupprimerMembre().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCheckBoxSupprimerActionPerformed

    private void jCheckBoxMettreAjourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMettreAjourActionPerformed
       new MettreAjourMembre().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jCheckBoxMettreAjourActionPerformed

    private void jCheckBoxAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAjouterActionPerformed
        new AjouterMembre().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCheckBoxAjouterActionPerformed

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void jCheckBoxRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRechercherActionPerformed
        new RechercherMembre().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jCheckBoxRechercherActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitter;
    private javax.swing.JCheckBoxMenuItem jCheckBoxAjouter;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMettreAjour;
    private javax.swing.JCheckBoxMenuItem jCheckBoxRechercher;
    private javax.swing.JCheckBoxMenuItem jCheckBoxSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
